apiVersion: v1
kind: Namespace
metadata:
  name: vbnvbn-prod
  labels:
    environment-id: env_e0fc0107-fcc6-43f5-8219-4772941acf90
    project-id: project_0cb00900-5aaf-4f8f-8e7d-6fb3297aea11
    project-name: vbnvbn
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
