apiVersion: v1
kind: Namespace
metadata:
  name: vbnvbn-dev
  labels:
    environment-id: env_47654023-849d-4fd6-b3c9-ae313aeb2514
    project-id: project_0cb00900-5aaf-4f8f-8e7d-6fb3297aea11
    project-name: vbnvbn
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
